/**
 * Generate Caddyfile content based on user configuration.
 */

interface Config {
  port: number;
  domain: string;
  email: string;
  https: boolean;
}

export function generateCaddyfile(config: Config): string {
  if (!config.https) {
    // Localhost mode: plain HTTP reverse proxy
    return `# Arthas Caddyfile — Local Development (generated by create-arthas)
:${config.port} {
    reverse_proxy arthas:8080
}
`;
  }

  // Production mode: auto HTTPS
  return `# Arthas Caddyfile — Production HTTPS (generated by create-arthas)
{
    email {$EMAIL}
}

{$DOMAIN} {
    reverse_proxy backend:8080

    header {
        X-Content-Type-Options nosniff
        X-Frame-Options DENY
        Referrer-Policy no-referrer
        -Server
    }
}
`;
}
