/**
 * Generate docker-compose.yml content based on user configuration.
 */

interface Config {
  port: number;
  domain: string;
  https: boolean;
  githubOwner: string;
  version: string;
}

export function generateDockerCompose(config: Config): string {
  const { https } = config;

  if (!https) {
    // Simple mode: just the backend, no Caddy
    return `# Arthas Self-Hosted (generated by create-arthas)
services:
  arthas:
    image: ghcr.io/\${GITHUB_OWNER}/arthas:\${ARTHAS_VERSION:-latest}
    container_name: arthas
    ports:
      - "\${PORT}:8080"
    environment:
      - PORT=8080
      - ALLOWED_ORIGINS=\${ALLOWED_ORIGINS:-*}
    read_only: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 3s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
`;
  }

  // Production mode: backend + Caddy for auto HTTPS
  return `# Arthas Self-Hosted with HTTPS (generated by create-arthas)
services:
  backend:
    image: ghcr.io/\${GITHUB_OWNER}/arthas:\${ARTHAS_VERSION:-latest}
    container_name: arthas-backend
    environment:
      - PORT=8080
      - ALLOWED_ORIGINS=https://\${DOMAIN}
    networks:
      - arthas-net
    read_only: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 3s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  caddy:
    image: caddy:2-alpine
    container_name: arthas-caddy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=\${DOMAIN}
      - EMAIL=\${EMAIL}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - arthas-net
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  arthas-net:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
`;
}
