/**
 * Generate .env file content based on user configuration.
 */

interface Config {
  port: number;
  domain: string;
  email: string;
  https: boolean;
  githubOwner: string;
  version: string;
}

export function generateEnv(config: Config): string {
  const lines: string[] = [
    '# Arthas Self-Hosted Configuration (generated by create-arthas)',
    '',
    `DOMAIN=${config.domain}`,
    `PORT=${config.port}`,
    `GITHUB_OWNER=${config.githubOwner}`,
    `ARTHAS_VERSION=${config.version}`,
  ];

  if (config.https && config.email) {
    lines.push(`EMAIL=${config.email}`);
  }

  if (!config.https) {
    lines.push('ALLOWED_ORIGINS=*');
  } else {
    lines.push(`ALLOWED_ORIGINS=https://${config.domain}`);
  }

  lines.push('');
  return lines.join('\n');
}
